# Generated by Django 4.1 on 2023-06-28 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nasa', '0002_alter_slider_options_slider_my_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ['order'], 'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='my_order',
            new_name='order',
        ),
    ]
